services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=test
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - drakina
  db:
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    networks:
      - drakina
volumes:
   db-data:
networks:
  drakina:
        